### ISSUE TITLE
Help to do some refactoring?

### ISSUE THREAD

**Issue by PedroSFreitas** [peterpt/eternal_scanner#1]
I recently created a PKGBUILD for BlackArch project (https://github.com/BlackArch/blackarch/pull/1739).
But after reading the source code I thought we could work on some refactoring. Would you like some help on that?
For example:

- Fixing indentation; and
- Better coding practices, like doubles quotes on some parts to avoid globing.

**Comment by peterpt** [comment]
Sure , but now it is not the good time because i am adding some features to the code .

- Scan user personal ip list from external file
- Splitting metasploit ipscan lists to 500 at time
(reason : script terminates itself if metasploit have to scan more than 700 ips)
- Probably will add also from terminal line an option to direct ip/iprange scan .
(ex: ./escan -s 5000 -i 192.168.1.1/24)

I will see if i can manage to code those changes during this week .

**Comment by PedroSFreitas** [comment]
> Note : to add escan to pkgbuild is better change escan working directories , instead working on current path , use a directory in /usr/share/escan .

Not sure if I'm following you on this, but the application isn't running from current path, but system wide path `/usr/bin` (/bin/).
I believe the `/usr/share` is for, as the name implies, shared resources. That is maybe where `elog` could be. And this leaves to another idea, why `elog` is separated from `escan`? I believe it's a small piece of code that could be inside `escan` for simplicity.

But alright, I'll wait your changes.
Good day.

(closing)

**Comment by peterpt** [comment]
Elog works outside escan so user be able to stop msfconsole script for big range of ips without stopping the escan script in the middle and break metasploit results .

**Comment by peterpt** [comment]
Version 2.0 have everything that escan should have , if you want to do some "refactoring" to the code , then clone up the git at this point to your github and send me your changes thru pull requests , and i will implement them as soon as i check them .
