### ISSUE TITLE
hello can you please tell me what is the problem 

### ISSUE THREAD

**Issue by J0ker07** [peterpt/eternal_scanner#3]
----------------------------
Collected 10 ips
 Checking if the 10 ips are vulnerable

 Press CTRL+C (1X ONLY) to stop ips vulnerability check
 (aborting this process will not verify all ips)

Please Wait , checking 10 ips may take a while
./escan: line 567: elog: command not found
cat: /usr/local/share/Eternal_Scanner/msflog.log: No such file or directory
cat: /usr/local/share/Eternal_Scanner/msflog.log: No such file or directory
cat: /usr/local/share/Eternal_Scanner/msflog.log: No such file or directory
cat: /usr/local/share/Eternal_Scanner/msflog.log: No such file or directory

 No vulnerable targets were detected from the list 
┌─[✗]─[root@parrot]─[~/eternal_scanner]
└──╼ #

**Comment by J0ker07** [comment]
I alraeady checked the msfcosole and its working good !

**Comment by peterpt** [comment]
your metasploit is not running properly in every place in your linux , so when elog tries to get the output from it , it can not find it and popup those errors .
do this : 
go to root fs directory
cd /
msfconsole


Note : you dont need to run escan on eternal scanner folder because it is already installed in your /usr/local/sbin

you can run escan anywhere in your linux

try to run msfconsole on the root folder /
and then exit it if it worked , and then run escan from there

**Comment by J0ker07** [comment]
Thank you so much 
It looks like i had a problem with installing the tool 

I've reinstalled it and it works so good 

Thx Bro
