### ISSUE TITLE
any help 

### ISSUE THREAD

**Issue by prince911** [peterpt/eternal_scanner#4]
Scanner results not found

what i messing 

i use linux mint

**Comment by peterpt** [comment]
Your metasploit is not running outside its own folder .
best way to check this is open a terminal and write this : 

cd /
msfconsole

if metasploit opens without any issue then run escan from there , else you must check your metasploit installation variable paths .
Best way to avois that issue is to install metasploit from repository , however , i think linux mint does not have metasploit package in their repository because linux mint is not a  pentest distribution .

**Comment by peterpt** [comment]
Sorry , mislead your output .
Scanner results not found is related to masscan issues .
Make sure you have the latest masscan installed because the old version of masscan pops up issues in some commands used by eternal scanner .
Debian sid and kali rolling have the latest masscan in their repositories , however if you are using an old linux distribution , you should consider compiling masscan  from the source here : 
https://github.com/robertdavidgraham/masscan
