### ISSUE TITLE
Opps , not connected to Internet

### ISSUE THREAD

**Issue by GenKoc** [peterpt/eternal_scanner#7]
Hi. Have a problem, when launch escan " Opps , not connected to Internet". But the connection is ok(i running msf, nmap and other programs). Where is the problem?

**Comment by peterpt** [comment]
Simple , on lines 721 , 734 , 748,844,920,959,995 
https://github.com/peterpt/eternal_scanner/blob/master/escan
eternal scanner does a checkup using netcat on google.com on port 80 (nc command) , if it is successfully then it continues , else it drops that message .
By default , netcat is installed in every linux OS , maybe in yours is not .

try : apt-get install netcat

I did not place a netcat checkup on the main script because by default is installed .

**Comment by GenKoc** [comment]
yeah. hadnt netcat on my vds)). Thanks!
